'use strict';

module.exports = {
  TEST_SERVER_PORTS: {
    DEFAULT: 8080,
    EXAMPLE: 8081,
    HEALTH_DB_CONNECTION_READY: 8082,
    HEALTH_DB_CONNECTION_NOT_READY: 8083,
    NOT_FOUND: 8084,
    CACHE_PLUGIN: 8090,
    ERROR_STANDARD_PLUGIN: 8091,
    REQUEST_RESPONSE_LOGGER_PLUGIN: 8092,
    GRACEFUL_SHUTDOWN_DEFAULT: 8093,
    GRACEFUL_SHUTDOWN_WITH_DELAY_CONFIGURATION: 8094,
    GRACEFUL_SHUTDOWN_WITH_APP_PROCESS_TERMINATED: 8095,
  },
};
